import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className={"max-w-sreen-xl mx-auto w-full overflow-auto"}>
        <header className="border-10 sticky top-0 z-10 border-b bg-white">
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
